<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>msh</string>
		<string>geo</string>
	</array>
	<key>name</key>
	<string>gmsh</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^---(?= |$)</string>
			<key>name</key>
			<string>entity.other.document-start.gmsh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.{3}$</string>
			<key>name</key>
			<string>entity.other.document-end.gmsh</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#MultipleLineComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#LineComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#GmshFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ExpressionFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#NormalFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#SelfFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Chars</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Expression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#OperatorKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ControlKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#OtherKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#OtherConstants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Variable</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>Chars</key>
		<dict>
			<key>match</key>
			<string>\'((\\\')*[^\'])*\'</string>
			<key>name</key>
			<string>string.quoted.single.gmsh</string>
		</dict>
		<key>Constants</key>
		<dict>
			<key>match</key>
			<string>\b(GMSH_MAJOR_VERSION|GMSH_MINOR_VERSION|GMSH_PATCH_VERSION|MPI_Size|MPI_Rank|Cpu|Memory|TotalMemory|lc|Pi|newp|newl|news|newv|newll|newsl|newreg|(-)?[0-9.]+|(-)?[0-9.]+e(-)?[0-9.]+)\b</string>
			<key>name</key>
			<string>constant.numeric.gmsh</string>
		</dict>
		<key>ControlKeywords</key>
		<dict>
			<key>match</key>
			<string>\b(Include|Error|Printf|Exit|Abort|Call|Return|ElseIf|For|In|EndFor|If|EndIf|Else)\s*</string>
			<key>name</key>
			<string>keyword.control.gmsh</string>
		</dict>
		<key>Expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#LineComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#MultipleLineComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#SelfFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#OperatorKeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ControlKeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#OtherKeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#OtherConstants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Variable</string>
				</dict>
			</array>
		</dict>
		<key>ExpressionFunctions</key>
		<dict>
			<key>begin</key>
			<string>(\b(Show|Hide|AdaptMesh|CombinedBoundary|Boundary|Extrude|Translate|BoundingBox|Duplicata|Rotate|Dilate|Symmetry|Transfinite\s+Surface|Recombine\s+Surface|Transfinite\s+Line))(\s*(\{))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.gmsh</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\s*(\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.gmsh</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#GmshFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Strings</string>
				</dict>
			</array>
		</dict>
		<key>GmshFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ExpressionFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#NormalFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#SelfFunctions</string>
				</dict>
			</array>
		</dict>
		<key>LineComments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.gmsh</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.gmsh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//.*)</string>
		</dict>
		<key>MultipleLineComments</key>
		<dict>
			<key>begin</key>
			<string>(/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*)</string>
			<key>end</key>
			<string>(\*+/)</string>
			<key>name</key>
			<string>comment.block.gmsh</string>
		</dict>
		<key>NormalFunctions</key>
		<dict>
			<key>begin</key>
			<string>(\b(SetNumber|SetString|Acos|Asin|Atan|Atan2|Ceil|Cos|Cosh|Exp|Fabs|Fmod|Floor|Hypot|Log|Log10|Modulo|Rand|Round|Sqrt|Sin|Sinh|Tan|Tanh|Delete|Compound\s+Line|Compound\s+Surface|Compound\s+Volume|Split\s+Line|Physical\s+Point|Physical\s+Line|Physical\s+Surface|Physical\s+Volume)(\s*\())</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.gmsh</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\s*(\)))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.gmsh</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#Functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gmshSyntaxing</string>
				</dict>
			</array>
		</dict>
		<key>OperatorKeywords</key>
		<dict>
			<key>match</key>
			<string>\s*(-|!|\+\+|--|\^|\*|%|\+|-|=|==|\+=|-=|\*=|/=|!=|&gt;|&gt;=|&lt;|&lt;=|&amp;&amp;|\|\||\?|:|#)\s*</string>
			<key>name</key>
			<string>keyword.operator.gmsh</string>
		</dict>
		<key>OtherConstants</key>
		<dict>
			<key>match</key>
			<string>\b(Mesh.SubdivisionAlgorithm|Physicals|Variables|Options|TotalMemory|Memory|Cpu|Pi|GMSH_MAJOR_VERSION|GMSH_MINOR_VERSION|GMSH_PATCH_VERSION|MPI_Size|MPI_Rank)\b</string>
			<key>name</key>
			<string>keyword.other.gmsh</string>
		</dict>
		<key>OtherKeywords</key>
		<dict>
			<key>match</key>
			<string>\b((Layers|Point|Spline|CatmullRom|Circle|Ellipse|BSpline|Ruled\s+Surface|Plane\s+Surface|Volume|Line\s+Loop|Line|Surface\s+Loop|Surface))\b</string>
			<key>name</key>
			<string>function.constant.gmsh</string>
		</dict>
		<key>PhysicalGroupTag</key>
		<dict>
			<key>match</key>
			<string>(\s*\$.*\$\s*)</string>
			<key>name</key>
			<string>keyword.other.gmsh</string>
		</dict>
		<key>SelfFunctions</key>
		<dict>
			<key>match</key>
			<string>(\b(RelocateMesh|SetOrder|Print|Sleep|SyatemCall|NonBlockingSystemCall|SetName|SyncModel|Macro|NewModel|Include|RefineMesh|Draw|Merge|Delete|BoundingBox|SetChanged|Show|Hide|CombinedBoundary|Boundary|Coherence|Transfinite\s+Line|Transfinite\s+Surface|Recombine\s+Surface|Recombine|)\b)</string>
			<key>name</key>
			<string>keyword.other.gmsh</string>
		</dict>
		<key>Strings</key>
		<dict>
			<key>match</key>
			<string>\"((\\\")*[^$\"])*\"</string>
			<key>name</key>
			<string>string.quoted.double.gmsh</string>
		</dict>
		<key>Variable</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>variable.parameter.gmsh</string>
		</dict>
		<key>gmshTag</key>
		<dict>
			<key>match</key>
			<string>\s*(Phy#|Enty#)\s*</string>
			<key>name</key>
			<string>keyword.other.gmsh</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.gmsh</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gmsh</string>
	<key>uuid</key>
	<string>b095c611-75c4-4280-af1f-72c1cac74826</string>
</dict>
</plist>
